fileName = "nokizaru.ini";
if (file_exists(fileName)) file_delete(fileName);
ini_open(fileName);
ini_write_real("player", "hp", obj_player.hp);
ini_write_real("player", "max_hp", obj_player.max_hp);
ini_write_bool("player", "walljump", obj_player.walljump);
ini_write_bool("player", "doublejump", obj_player.doublejump);
ini_write_bool("player", "fireball", obj_player.fireball);
ini_write_bool("player", "hpupgrade", obj_player.hpupgrade);
ini_write_bool("player", "backtrack", obj_player.backtrack);
ini_close();
